/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Category, Layanan, Article, Review } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Obat Bebas',
    slug: 'obat-bebas',
    icon: 'Pill',
    description: 'Obat-obatan ringan yang dapat dibeli tanpa resep dokter.',
    count: 145,
  },
  {
    id: 'cat-2',
    name: 'Vitamin & Suplemen',
    slug: 'vitamin-suplemen',
    icon: 'Activity',
    description: 'Suplemen multivitamin dan penambah imun tubuh harian.',
    count: 82,
  },
  {
    id: 'cat-3',
    name: 'Alat Kesehatan',
    slug: 'alat-kesehatan',
    icon: 'Thermometer',
    description: 'Alat pengukur suhu, tekanan darah, masker, dan P3K.',
    count: 48,
  },
  {
    id: 'cat-4',
    name: 'Perawatan Tubuh',
    slug: 'perawatan-tubuh',
    icon: 'Sparkles',
    description: 'Sabun medis, lotion kulit sensitif, dan perawatan rambut.',
    count: 95,
  },
  {
    id: 'cat-5',
    name: 'Ibu & Anak',
    slug: 'ibu-anak',
    icon: 'Baby',
    description: 'Susu formula, minyak telon, popok, dan kebutuhan bayi.',
    count: 73,
  },
  {
    id: 'cat-6',
    name: 'Herbal',
    slug: 'herbal',
    icon: 'Leaf',
    description: 'Minyak kayu putih, madu murni, obat herbal alami tradisional.',
    count: 54,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Blackmores Multivitamins + Minerals',
    price: 184000,
    originalPrice: 230000,
    description: 'Multivitamin lengkap untuk memenuhi kebutuhan vitamin dan mineral harian guna menjaga kebugaran tubuh secara maksimal.',
    category: 'vitamin-suplemen',
    image: 'https://images.unsplash.com/photo-1616671289397-0d47706d38e7?auto=format&fit=crop&q=80&w=400',
    isPromo: true,
    discountPercent: 20,
    unit: 'Botol (30 Tablet)',
    dosage: '1 tablet per hari setelah makan',
    indication: 'Menjaga stamina, melengkapi nutrisi harian yang kurang.',
    stock: 25,
  },
  {
    id: 'prod-2',
    name: 'You C1000 Orange Vitamin Drink',
    price: 7200,
    originalPrice: 8500,
    description: 'Minuman kesehatan dengan kandungan Vitamin C 1000mg yang segar dan membantu menjaga daya tahan tubuh setiap hari.',
    category: 'vitamin-suplemen',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    isPromo: true,
    discountPercent: 15,
    unit: 'Botol Kaca (140ml)',
    dosage: 'Dapat diminum dingin 1 botol sehari',
    indication: 'Mencegah sariawan, memelihara kesehatan kulit dan imun.',
    stock: 120,
  },
  {
    id: 'prod-3',
    name: 'Paramex Sakit Kepala',
    price: 3500,
    originalPrice: 4200,
    description: 'Obat sakit kepala legendaris yang cepat meredakan sakit kepala mencengkram, sakit gigi, dan demam.',
    category: 'obat-bebas',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
    isPromo: true,
    discountPercent: 15,
    unit: 'Strip (4 Tablet)',
    dosage: 'Dewasa: 2-3 kali sehari 1 tablet sesudah makan',
    indication: 'Meringankan sakit kepala dan sakit gigi.',
    stock: 200,
  },
  {
    id: 'prod-4',
    name: 'Biogesic Paracetamol 500mg',
    price: 12000,
    description: 'Paracetamol murni berkualitas tinggi yang aman di lambung untuk mengatasi demam, pusing, nyeri otot, dan pegal linu.',
    category: 'obat-bebas',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&q=80&w=400',
    isPromo: false,
    unit: 'Strip (10 Tablet)',
    dosage: 'Dewasa: 1-2 tablet, 3-4 kali sehari jika dibutuhkan',
    indication: 'Penurun demam dan pereda nyeri skala ringan-sedang.',
    stock: 150,
  },
  {
    id: 'prod-5',
    name: 'Omron Digital Blood Pressure HEM-7120',
    price: 645000,
    originalPrice: 720000,
    description: 'Alat tensimeter digital lengan atas yang sangat akurat, mudah digunakan, dan dilengkapi indikator detak jantung tidak teratur.',
    category: 'alat-kesehatan',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&q=80&w=400',
    isPromo: true,
    discountPercent: 10,
    unit: 'Box (1 Unit Tensimeter)',
    dosage: 'Gunakan sesuai instruksi manual pada lengan atas',
    indication: 'Memantau tekanan darah sistolik & diastolik secara mandiri.',
    stock: 12,
  },
  {
    id: 'prod-6',
    name: 'Termometer Digital Omron Pencil Eco Temp II',
    price: 95000,
    description: 'Termometer digital tahan air dengan ujung bulat fleksibel untuk pengukuran suhu ketiak, oral, maupun rektal secara cepat.',
    category: 'alat-kesehatan',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    isPromo: false,
    unit: 'Pcs',
    dosage: 'Tempelkan di ketiak hingga terdengar bunyi alarm bip',
    indication: 'Mengukur suhu tubuh dengan akurasi tinggi.',
    stock: 35,
  },
  {
    id: 'prod-7',
    name: 'Minyak Telon My Baby Plus Eucalyptus 150ml',
    price: 43500,
    description: 'Minyak telon bayi dengan keharuman khas yang menghangatkan perut bayi dan memberikan perlindungan 8 jam dari gigitan nyamuk.',
    category: 'ibu-anak',
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=400',
    isPromo: false,
    unit: 'Botol (150ml)',
    dosage: 'Oleskan secukupnya pada dada, perut, punggung, dan telapak kaki bayi setelah mandi',
    indication: 'Menghangatkan tubuh bayi, meredakan kembung, mencegah nyamuk.',
    stock: 60,
  },
  {
    id: 'prod-8',
    name: 'Tolak Angin Sido Muncul Cair',
    price: 24000,
    originalPrice: 28000,
    description: 'Suplemen herbal terstandar dari ekstrak bahan alami untuk mengatasi masuk angin, perut mual, kembung, dan pusing karena kelelahan.',
    category: 'herbal',
    image: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&q=80&w=400',
    isPromo: true,
    discountPercent: 14,
    unit: 'Kotak (12 Sachet)',
    dosage: 'Minum langsung atau seduh dengan air hangat, 1-3 sachet sehari',
    indication: 'Meredakan masuk angin, mabuk perjalanan, menjaga daya tahan tubuh.',
    stock: 180,
  },
  {
    id: 'prod-9',
    name: 'Cetaphil Gentle Skin Cleanser',
    price: 135000,
    description: 'Pembersih wajah legendaris berformula lembut, hypoallergenic, non-comedogenic, sangat cocok untuk kulit sensitif maupun berjerawat.',
    category: 'perawatan-tubuh',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&q=80&w=400',
    isPromo: false,
    unit: 'Botol (250ml)',
    dosage: 'Gunakan pagi dan malam dengan atau tanpa air',
    indication: 'Membersihkan kotoran dan menjaga kelembaban alami kulit.',
    stock: 42,
  },
  {
    id: 'prod-10',
    name: 'Madu TJ Murni Alami Sachet',
    price: 18500,
    description: 'Madu murni 100% kaya akan vitamin, mineral, dan enzim aktif untuk meningkatkan imunitas tubuh dan memulihkan stamina lesu.',
    category: 'herbal',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=400',
    isPromo: false,
    unit: 'Kotak (12 Sachet)',
    dosage: '3 kali sehari 1 sachet langsung atau dicampur teh/air',
    indication: 'Menjaga stamina tubuh, memulihkan pasca sakit.',
    stock: 90,
  }
];

export const LAYANAN_LIST: Layanan[] = [
  {
    id: 'lay-1',
    title: 'Konsultasi Apoteker',
    description: 'Konsultasi gratis mengenai penggunaan, dosis, dan efek samping obat bersama apoteker profesional kami.',
    iconName: 'UserCheck',
    details: [
      'Konsultasi via Chat WhatsApp 24/7',
      'Penjelasan dosis dan interaksi antar obat',
      'Rekomendasi suplemen sesuai riwayat kesehatan',
      'Privasi percakapan aman'
    ],
  },
  {
    id: 'lay-2',
    title: 'Cek Kesehatan',
    description: 'Cek kondisi tubuh dasar seperti tekanan darah, kadar gula darah, kolesterol, dan asam urat secara instan.',
    iconName: 'HeartPulse',
    details: [
      'Cek tensi darah gratis di apotek',
      'Tes darah kapiler (Gula, Kolesterol, Asam Urat)',
      'Hanya perlu waktu 5 menit',
      'Dilakukan oleh tenaga medis bersertifikat'
    ],
  },
  {
    id: 'lay-3',
    title: 'Antar Obat (Delivery)',
    description: 'Layanan pesan antar obat langsung ke rumah Anda dengan cepat dan kemasan aman bersegel.',
    iconName: 'Truck',
    details: [
      'Bebas biaya antar radius 5 KM',
      'Kemasan tersegel rapat dan buram untuk privasi',
      'Pengiriman kilat dalam waktu 1-2 jam',
      'Pembayaran COD atau Transfer Bank'
    ],
  },
  {
    id: 'lay-4',
    title: 'Penebusan Resep Dokter',
    description: 'Layanan tebus resep dokter terpercaya dengan pengecekan resep ketat demi keselamatan konsumsi.',
    iconName: 'FileText',
    details: [
      'Kirim foto resep dokter secara online',
      'Verifikasi keaslian resep oleh Apoteker senior',
      'Penyediaan obat racikan sesuai petunjuk spesifik',
      'Label botol/etiket obat yang sangat jelas'
    ],
  },
];

export const ARTICLES: Article[] = [
  {
    id: 'art-1',
    title: '5 Cara Ampuh Jaga Imun Tubuh Saat Musim Pancaroba',
    excerpt: 'Musim hujan yang tak menentu membuat tubuh rentan terkena penyakit. Simak tips praktis menjaga imun agar tetap bugar.',
    content: 'Pancaroba seringkali membawa fluktuasi cuaca ekstrem yang memicu berkembang biaknya virus dan bakteri. Untuk melindungi diri, Anda dianjurkan untuk:\n\n1. Mengonsumsi makanan padat nutrisi dengan kandungan zinc tinggi.\n2. Mengonsumsi suplemen multivitamin penunjang seperti Vitamin C dan D3.\n3. Tidur teratur minimal 7-8 jam per malam untuk regenerasi sel imun.\n4. Minum air putih minimal 2 liter per hari.\n5. Berolahraga intensitas ringan secara konsisten.',
    category: 'Kesehatan Umum',
    date: '25 Juni 2026',
    readTime: '3 Menit Baca',
    author: 'Apoteker Nabila S.Farm',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'art-2',
    title: 'Mengenal Perbedaan Kode Warna pada Lingkaran Kemasan Obat',
    excerpt: 'Jangan salah beli! Kenali perbedaan lingkaran hijau, biru, merah dengan huruf K, dan lambang pohon kelapa pada kemasan obat.',
    content: 'Sebelum membeli obat, Anda wajib memperhatikan tanda lingkaran pada kemasan:\n\n- **Lingkaran Hijau dengan Garis Tepi Hitam**: Obat Bebas, dapat dibeli tanpa resep dokter.\n- **Lingkaran Biru dengan Garis Tepi Hitam**: Obat Bebas Terbatas, dapat dibeli tanpa resep namun memiliki tanda peringatan khusus.\n- **Lingkaran Merah dengan Huruf K**: Obat Keras, wajib ditebus menggunakan resep dokter resmi.\n- **Logo Pohon Kelapa/Hijau Alami**: Obat Herbal/Jamu terstandar.',
    category: 'Edukasi Obat',
    date: '18 Juni 2026',
    readTime: '4 Menit Baca',
    author: 'Apoteker Hendra M.Sc',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'art-3',
    title: 'Mengapa Vitamin C Sangat Penting untuk Tubuh Kita?',
    excerpt: 'Vitamin C adalah antioksidan kuat yang tidak diproduksi alami oleh tubuh. Berapa dosis harian yang ideal?',
    content: 'Tubuh manusia tidak dapat memproduksi atau menyimpan vitamin C sendiri, sehingga pasokan dari luar sangatlah krusial. Perannya mencakup:\n\n1. Pembentukan kolagen kulit dan jaringan ikat.\n2. Mempercepat proses penyembuhan luka.\n3. Meningkatkan penyerapan zat besi dari makanan nabati.\n4. Menangkal radikal bebas berbahaya.\n\nDosis harian umum untuk dewasa berkisar antara 75-90mg, namun pada masa pemulihan dapat ditingkatkan hingga 500-1000mg atas saran medis.',
    category: 'Nutrisi & Suplemen',
    date: '10 Juni 2026',
    readTime: '3 Menit Baca',
    author: 'Apoteker Nabila S.Farm',
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&q=80&w=600',
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    name: 'Andi Wijaya',
    rating: 5,
    comment: 'Layanan konsultasi apoteker via WhatsApp sangat responsif dan informatif! Penjelasan aturan minum obat antibiotik untuk anak saya sangat jelas dan mendalam. Terima kasih Apotek Sehat!',
    date: '20 Juni 2026',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100',
  },
  {
    id: 'rev-2',
    name: 'Dewi Lestari',
    rating: 5,
    comment: 'Proses penebusan resep dokter di sini super cepat. Cukup upload foto resep lewat website ini, lalu tim apotek langsung menghubungi saya untuk verifikasi harga, dan dalam 1 jam obat racikan sudah diantar ke rumah saya dengan packaging aman bersegel.',
    date: '15 Juni 2026',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100',
  },
  {
    id: 'rev-3',
    name: 'Budi Santoso',
    rating: 5,
    comment: 'Pilihan obat bebas dan vitaminnya sangat lengkap. Harganya jauh lebih murah dibanding apotek lain, dan yang terpenting semua produk dijamin 100% original. Tokonya juga bersih dan nyaman.',
    date: '08 Juni 2026',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100',
  }
];
